on: [push]
name: CI
jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          component: clippy rustfmt
      - name: Install just
        uses: extractions/setup-just@v1
      - name: Install nextest
        uses: taiki-e/install-action@nextest

      - name: Run linting
        run: just lint

      - name: Run tests
        run: just test
