---
name: Release
on:
  workflow_run:
    workflows: [Test]
    types:
      - completed
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: taiki-e/install-action@just
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl

      - name: Setup MUSL
        run: sudo apt update && apt install -y musl-tools

      - name: Build Release
        run: just build-linux-musl-release

      - name: Check binary
        run: |
          ./target/x86_64-unknown-linux-musl/release/icbtask --version
          ls -l ./target/x86_64-unknown-linux-musl/release/gitui

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build Release
        run: just build-release

      - name: Check binary
        run: |
          ./target/x86_64-unknown-linux-musl/release/icbtask --version
          ls -l ./target/x86_64-unknown-linux-musl/release/gitui
