---
name: Release
on:
  push:
    tags:
      - "v*"
jobs:
  build-linux:
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: taiki-e/install-action@just
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl

      - name: Setup build env
        run: |
          sudo apt update
          sudo apt install -y musl-tools perl libssl-dev make

      - name: Build Release
        run: just build-release-linux

      - name: Check binary
        run: |
          ./target/x86_64-unknown-linux-musl/release/icbtask --version
          file ./target/x86_64-unknown-linux-musl/release/icbtask

  build-macos:
    needs: Test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - uses: taiki-e/install-action@just
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build Release
        run: just build-release

      - name: Check binary
        run: |
          ./target/release/icbtask --version
